// Code generated by internal/errs/gen from spec/errors.json. DO NOT EDIT.
module.exports = { CODES: {
  "HB-APPKEY-INVALID": {
    "code": "HB-APPKEY-INVALID",
    "title": "Application key is not valid",
    "problem": "the application key is not valid",
    "cause": "An application key is 64 lowercase hex digits. A copied key may be cut short or use capital letters.",
    "fix": "Scan the host's QR code again, or copy the application key again from holebridge app-key on the host.",
    "where": [
      "go",
      "engine"
    ]
  },
  "HB-APPKEY-MISSING": {
    "code": "HB-APPKEY-MISSING",
    "title": "No application key",
    "problem": "there is no application key for this deployment",
    "cause": "Each deployment has one application key. It is made at install or first run, and an app gets it from a host's QR code or link.",
    "fix": "On the host, run holebridge app-key --new to create one. In the app, scan the host's QR code or open its link.",
    "where": [
      "go",
      "app"
    ]
  },
  "HB-APPKEY-PERMS": {
    "code": "HB-APPKEY-PERMS",
    "title": "app.key readable by others",
    "problem": "app.key can be read by other users",
    "cause": "The file holds the application key, a secret for the whole deployment. The host and the relay will not start while others can read it.",
    "fix": "chmod 600 ~/.config/holebridge/app.key",
    "where": [
      "go"
    ]
  },
  "HB-CONFIG-DIR-PERMS": {
    "code": "HB-CONFIG-DIR-PERMS",
    "title": "Config directory not owner-only",
    "problem": "the config directory is not owner-only",
    "cause": "The control socket lives in the config directory. The host and the relay do not serve while other users can enter it, or while another user owns it.",
    "fix": "chmod 700 ~/.config/holebridge",
    "where": [
      "go"
    ]
  },
  "HB-CONFIG-INVALID": {
    "code": "HB-CONFIG-INVALID",
    "title": "Config is not valid",
    "problem": "the configuration is not valid",
    "cause": "A value in host.json is missing or wrong, or no config directory is set. The detail names what is wrong.",
    "fix": "Fix the value the detail names, in host.json, or set --config or HOLEBRIDGE_CONFIG.",
    "where": [
      "go"
    ]
  },
  "HB-CONFIG-PERMS": {
    "code": "HB-CONFIG-PERMS",
    "title": "host.json readable by others",
    "problem": "host.json can be read by other users",
    "cause": "The file holds the host key.",
    "fix": "chmod 600 ~/.config/holebridge/host.json",
    "where": [
      "go"
    ]
  },
  "HB-ENGINE-DOWN": {
    "code": "HB-ENGINE-DOWN",
    "title": "Engine not running",
    "problem": "the app engine stopped and could not be started again",
    "cause": "The engine runs inside the app. It exited, and starting it again failed, for example because the system is short of memory.",
    "fix": "Close the app and open it again. If it keeps happening, report it with this code.",
    "where": [
      "app"
    ]
  },
  "HB-HANDOFF-EXPIRED": {
    "code": "HB-HANDOFF-EXPIRED",
    "title": "Pairing code expired",
    "problem": "the pairing code timed out",
    "cause": "A pairing code works for 5 minutes, so an old code is not accepted.",
    "fix": "On the TV, choose Add from phone again to show a new code.",
    "where": [
      "app"
    ]
  },
  "HB-HANDOFF-REFUSED": {
    "code": "HB-HANDOFF-REFUSED",
    "title": "TV refused the host",
    "problem": "the TV did not accept the host",
    "cause": "A TV accepts a host only from a phone that scanned the code it is showing now. The code on the phone is old, or it came from another TV.",
    "fix": "On the TV, choose Add from phone to show a new code, then scan that code with the phone.",
    "where": [
      "app"
    ]
  },
  "HB-HANDOFF-UNREACHABLE": {
    "code": "HB-HANDOFF-UNREACHABLE",
    "title": "Phone cannot reach the TV",
    "problem": "the phone cannot reach the TV",
    "cause": "The phone and the TV are not on the same network, or the network keeps devices apart. Guest networks often do.",
    "fix": "Use the same network, not a guest network with client isolation.",
    "where": [
      "app"
    ]
  },
  "HB-IPC-DESYNC": {
    "code": "HB-IPC-DESYNC",
    "title": "Engine output out of step",
    "problem": "a malformed frame arrived on the worklet's stdout",
    "cause": "Native code can still write to fd 1 directly.",
    "fix": "The app restarts its engine on its own. If this keeps happening, report it with this code.",
    "where": [
      "app"
    ]
  },
  "HB-KEY-INVALID": {
    "code": "HB-KEY-INVALID",
    "title": "Key is not valid",
    "problem": "the key is not valid",
    "cause": "A key is 9 symbols from 0 to 9 and A to Z, except U. Case, dashes and spaces do not matter.",
    "fix": "Type the key shown by holebridge key on the host, or scan its QR code.",
    "where": [
      "go",
      "engine",
      "app"
    ]
  },
  "HB-LAN-PORT-IN-USE": {
    "code": "HB-LAN-PORT-IN-USE",
    "title": "LAN port already in use",
    "problem": "a LAN port is already taken",
    "cause": "Another program, or a second host on this machine, is using the port.",
    "fix": "Stop the other program, or set other lan.port and lan.discoveryPort values in host.json.",
    "where": [
      "go"
    ]
  },
  "HB-LIMIT-REACHED": {
    "code": "HB-LIMIT-REACHED",
    "title": "Connection limit reached",
    "problem": "the host is at one of its limits",
    "cause": "Too many connections or streams are open at once. The host caps them so that no one client can use up its resources.",
    "fix": "Close some connections and try again. The host owner can raise a limit under limits in host.json.",
    "where": [
      "go",
      "app"
    ]
  },
  "HB-LOOKUP-TIMEOUT": {
    "code": "HB-LOOKUP-TIMEOUT",
    "title": "Host not found",
    "problem": "the app could not reach the host",
    "cause": "No host answered for this key. The host may be off, the key may be mistyped or from another deployment, or the network may block the connection.",
    "fix": "Check that the host is running and that the key is right. The app keeps trying on its own.",
    "where": [
      "app"
    ]
  },
  "HB-NOT-RUNNING": {
    "code": "HB-NOT-RUNNING",
    "title": "Not running",
    "problem": "holebridge is not running",
    "cause": "holebridge status reads the control socket of a running host or relay in this config directory. No socket answers, so none is running here.",
    "fix": "Start one with holebridge host or holebridge relay, or pass --config for the directory of the one that runs.",
    "where": [
      "go"
    ]
  },
  "HB-RELAY-KEY-MISSING": {
    "code": "HB-RELAY-KEY-MISSING",
    "title": "No relay key",
    "problem": "there is no relay key in the config directory",
    "cause": "A relay runs under the relay key in relay.key. The hosts and apps that use the relay need the same key.",
    "fix": "Run holebridge relay --new-key to create relay.key, then put the same key in host.json (relay) and in the app under Settings, Relay.",
    "where": [
      "go"
    ]
  },
  "HB-RELAY-KEY-PERMS": {
    "code": "HB-RELAY-KEY-PERMS",
    "title": "relay.key readable by others",
    "problem": "relay.key can be read by other users",
    "cause": "The file holds the relay key, and anyone who has it can use the relay. The relay and relay check do not run while others can read it.",
    "fix": "chmod 600 ~/.config/holebridge/relay.key, or the file given to relay check",
    "where": [
      "go"
    ]
  },
  "HB-RELAY-REFUSED": {
    "code": "HB-RELAY-REFUSED",
    "title": "Relay refused the connection",
    "problem": "the relay did not accept this key",
    "cause": "Only one side has the relay key, or the two sides have different relay keys.",
    "fix": "Put the same relay key in host.json (relay) and in the app under Settings, Relay.",
    "where": [
      "go",
      "app"
    ]
  },
  "HB-TARGET-REFUSED": {
    "code": "HB-TARGET-REFUSED",
    "title": "Service refused the connection",
    "problem": "the service refused the connection",
    "cause": "Nothing is listening at the service's target, or the service turned the connection down.",
    "fix": "Start the service, or correct its target in host.json.",
    "where": [
      "go",
      "app"
    ]
  },
  "HB-TARGET-TIMEOUT": {
    "code": "HB-TARGET-TIMEOUT",
    "title": "Service did not answer in time",
    "problem": "the service did not answer in time",
    "cause": "The host could not connect to the service within 10 seconds. The service may be busy or stopped, or its target may be wrong.",
    "fix": "Check that the service is running and that its target in host.json is right.",
    "where": [
      "go",
      "app"
    ]
  },
  "HB-UDP-TOO-LARGE": {
    "code": "HB-UDP-TOO-LARGE",
    "title": "UDP datagram too large",
    "problem": "a datagram is larger than maxDatagram (1144 bytes by default)",
    "cause": "A UDP datagram must fit in one encrypted packet. Larger ones are dropped, because HoleBridge does not split them.",
    "fix": "Make the application send smaller UDP packets.",
    "where": [
      "app"
    ]
  },
  "HB-UNKNOWN-SERVICE": {
    "code": "HB-UNKNOWN-SERVICE",
    "title": "Unknown service",
    "problem": "the host has no service with this name",
    "cause": "The name is not in the host's service list, or the app's copy of the list is out of date.",
    "fix": "Check the name with holebridge service ls on the host, then reconnect the app.",
    "where": [
      "go",
      "app"
    ]
  },
  "HB-USAGE": {
    "code": "HB-USAGE",
    "title": "Bad command line",
    "problem": "the command line is not valid",
    "cause": "A command, option or value is missing or not known.",
    "fix": "Run holebridge --help to see the commands and options.",
    "where": [
      "go"
    ]
  },
  "HB-VERSION-MISMATCH": {
    "code": "HB-VERSION-MISMATCH",
    "title": "App and host versions differ",
    "problem": "the app and the host speak different protocol versions",
    "cause": "The app and the host run different protocol versions, which may not work together.",
    "fix": "Update the app from its store, or re-run the install script on the host.",
    "where": [
      "go",
      "app"
    ]
  }
} };
