package udx

import "testing"

// The expected values in this file come from libudx ae8bff7 (src/udx_bbr.c). Each scenario was
// run through a C harness in the session scratchpad that includes udx_bbr.c, built with clang
// against the upstream headers and libuv. The harness stubs udx__max_payload (1152 bytes, the
// udx.c value for mtu 1200 over IPv4) and udx_rtt_min, and sets the loop time that uv_now reads.
// The rate samples are given, not generated by udx_rate.c. Times are in ms. Each scenario's
// comment names its upstream run.

// bbrAck is one ack event as the ack path presents it to bbr_main: the stream's delivered and
// in-flight counts after the acks, the delivery time (the event time), then the rate sample.
func bbrAck(f *bbrFlow, nowMS uint64, delivered, inflight uint32, rs rateSample) {
	f.rate.delivered = delivered
	f.rate.deliveredTS = nowMS
	f.inflight = inflight
	f.onRateSample(&rs, nowMS)
}

// bbrWant is the BBR state after one step, for the fields every step checks.
type bbrWant struct {
	state    uint8
	cycle    uint8
	cwnd     uint32
	pacing   uint32
	bw       float64
	minRTT   uint32
	minStamp uint64
	fullBW   bool
}

// checkBBR compares the core state after the step named step.
func checkBBR(t *testing.T, f *bbrFlow, step string, w bbrWant) {
	t.Helper()
	got := bbrWant{
		state:    f.bbr.state,
		cycle:    f.bbr.cycleIndex,
		cwnd:     f.cwnd,
		pacing:   f.pacingBytesPerMS,
		bw:       f.bbr.bw.get(),
		minRTT:   f.bbr.minRTTms,
		minStamp: f.bbr.minRTTStamp,
		fullBW:   f.bbr.fullBWReached,
	}
	if got != w {
		t.Errorf("%s: state = %+v, want %+v", step, got, w)
	}
}

// wantEq compares one more field of a step.
func wantEq[T comparable](t *testing.T, step, field string, got, want T) {
	t.Helper()
	if got != want {
		t.Errorf("%s: %s = %v, want %v", step, field, got, want)
	}
}

// STARTUP growth to full bandwidth, DRAIN, then PROBE_BW. Each ack event is one packet-timed
// round.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRStartupDrainProbeBWLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "init", "hasrtt", f.bbr.hasSeenRTT, true)
	wantEq(t, "init", "epochstart", f.bbr.ackEpochStart, 1000)
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1050", "rttcount", f.bbr.rttCount, 1)
	wantEq(t, "ack 1050", "delivered", f.rate.delivered, 50)
	wantEq(t, "ack 1050", "gainp", f.bbr.pacingGain, float32(2.88539004))
	wantEq(t, "ack 1050", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 400, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrDrain, cycle: 0, cwnd: 777, pacing: 1581, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1350", "gainp", f.bbr.pacingGain, float32(0.346573591))
	wantEq(t, "ack 1350", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1400, 1300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "gainp", f.bbr.pacingGain, float32(1))
	wantEq(t, "ack 1400", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1450, 1500, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1450", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
}

// PROBE_BW gain cycle after the ramp: phases advance once per 60 ms (more than the 50 ms min RTT).
// The 1.25 phase holds until the in-flight count exceeds its BDP, the 0.75 phase ends at once. An
// app-limited sample that is below the max bandwidth is ignored, and a transmit start after app
// limiting restarts the ack epoch.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRProbeBWGainCycleLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1050", "rttcount", f.bbr.rttCount, 1)
	wantEq(t, "ack 1050", "delivered", f.rate.delivered, 50)
	wantEq(t, "ack 1050", "gainp", f.bbr.pacingGain, float32(2.88539004))
	wantEq(t, "ack 1050", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 400, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrDrain, cycle: 0, cwnd: 777, pacing: 1581, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1350", "gainp", f.bbr.pacingGain, float32(0.346573591))
	wantEq(t, "ack 1350", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1400, 1300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "gainp", f.bbr.pacingGain, float32(1))
	wantEq(t, "ack 1400", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1460, 1700, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1460", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1520, 1900, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1520", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1580, 2100, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1580", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1640, 2300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1640", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 600, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1640", "gainp", f.bbr.pacingGain, float32(1.25))
	wantEq(t, "ack 1640", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1700, 2500, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1700", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 600, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1760, 2700, 300, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1760", bbrWant{state: bbrProbeBW, cycle: 1, cwnd: 600, pacing: 3421, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1820, 2900, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1820", bbrWant{state: bbrProbeBW, cycle: 2, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1880, 3100, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2900, ackedSacked: 200, losses: 1, rttMS: 50})
	checkBBR(t, f, "ack 1880", bbrWant{state: bbrProbeBW, cycle: 3, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1940, 3200, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 3100, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1940", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	f.rate.appLimited = 5000
	f.onTransmitStart(2000)
	checkBBR(t, f, "start 2000", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "start 2000", "idle", f.bbr.idleRestart, true)
	wantEq(t, "start 2000", "epochstart", f.bbr.ackEpochStart, 2000)
	wantEq(t, "start 2000", "epochacked", f.bbr.ackEpochAcked, 0)
}

// The min RTT filter expires after 10 s, so the sender enters PROBE_RTT and caps the window at 4.
// It leaves once the in-flight count has been at most 4 for 200 ms and a packet-timed round has
// passed.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRProbeRTTLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 100, 10, rateSample{intervalMS: 50, delivered: 100, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 110, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 11050, 200, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 100, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11050", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 6581, bw: 2.0, minRTT: 60, minStamp: 11050, fullBW: false})
	wantEq(t, "ack 11050", "probedone", f.bbr.probeRTTDoneTime, 0)
	wantEq(t, "ack 11050", "priorcwnd", f.bbr.priorCwnd, 110)
	wantEq(t, "ack 11050", "appl", f.rate.appLimited, 210)
	bbrAck(f, 11100, 300, 4, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 200, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11100", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 6581, bw: 2.0, minRTT: 60, minStamp: 11050, fullBW: false})
	wantEq(t, "ack 11100", "probedone", f.bbr.probeRTTDoneTime, 11300)
	wantEq(t, "ack 11100", "appl", f.rate.appLimited, 304)
	bbrAck(f, 11150, 400, 4, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 300, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11150", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 2280, bw: 2.0, minRTT: 60, minStamp: 11050, fullBW: true})
	wantEq(t, "ack 11150", "probedone", f.bbr.probeRTTDoneTime, 11300)
	bbrAck(f, 11250, 500, 4, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 400, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11250", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 2280, bw: 2.0, minRTT: 60, minStamp: 11050, fullBW: true})
	wantEq(t, "ack 11250", "probedone", f.bbr.probeRTTDoneTime, 11300)
	bbrAck(f, 11350, 600, 4, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 500, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11350", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 210, pacing: 2280, bw: 2.0, minRTT: 60, minStamp: 11350, fullBW: true})
	wantEq(t, "ack 11350", "probedone", f.bbr.probeRTTDoneTime, 11300)
	bbrAck(f, 11400, 700, 40, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 600, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 310, pacing: 2280, bw: 2.0, minRTT: 60, minStamp: 11350, fullBW: true})
}

// Min RTT rules: a lower sample always counts, an ack-delayed sample does not replace a min after
// the filter expires, and a 0 ms sample becomes 1 ms. A negative RTT (no sample) changes nothing.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRMinRTTRulesLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 100, 10, rateSample{intervalMS: 50, delivered: 100, ackedSacked: 100, rttMS: 40})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 110, pacing: 6581, bw: 2.0, minRTT: 40, minStamp: 1050, fullBW: false})
	bbrAck(f, 1100, 200, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 100, ackedSacked: 100, rttMS: 30, isAckDelayed: true})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 210, pacing: 6581, bw: 2.0, minRTT: 30, minStamp: 1100, fullBW: false})
	bbrAck(f, 11200, 300, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 200, ackedSacked: 100, rttMS: 60, isAckDelayed: true})
	checkBBR(t, f, "ack 11200", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 6581, bw: 2.0, minRTT: 30, minStamp: 1100, fullBW: false})
	wantEq(t, "ack 11200", "probedone", f.bbr.probeRTTDoneTime, 0)
	bbrAck(f, 11250, 400, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 300, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11250", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 2280, bw: 2.0, minRTT: 60, minStamp: 11250, fullBW: true})
	bbrAck(f, 11300, 500, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 400, ackedSacked: 100, rttMS: 0})
	checkBBR(t, f, "ack 11300", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 2280, bw: 2.0, minRTT: 1, minStamp: 11300, fullBW: true})
	bbrAck(f, 11350, 600, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 500, ackedSacked: 100, rttMS: -1})
	checkBBR(t, f, "ack 11350", bbrWant{state: bbrProbeRTT, cycle: 0, cwnd: 4, pacing: 2280, bw: 2.0, minRTT: 1, minStamp: 11300, fullBW: true})
}

// Loss recovery: bbr_save_cwnd keeps the window to restore, an RTO sets the previous CA state to
// LOSS, entering RECOVERY uses packet conservation (the window is the packets in flight plus the
// acks), and leaving RECOVERY for OPEN restores the saved window when the window has fallen below
// it. Packet conservation ends at the next packet-timed round, and a second recovery is entered
// from OPEN.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRRecoveryAndRestoreLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	f.saveCwnd()
	checkBBR(t, f, "save", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "save", "priorcwnd", f.bbr.priorCwnd, 510)
	f.onRTO()
	checkBBR(t, f, "rto", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "rto", "prevca", f.bbr.prevCAState, 3)
	wantEq(t, "rto", "pc", f.bbr.usePacketConservation, false)
	f.caState = caRecovery
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, losses: 2, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 320, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1250", "prevca", f.bbr.prevCAState, 2)
	wantEq(t, "ack 1250", "pc", f.bbr.usePacketConservation, true)
	wantEq(t, "ack 1250", "priorcwnd", f.bbr.priorCwnd, 510)
	f.caState = caOpen
	bbrAck(f, 1300, 900, 130, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1300", "prevca", f.bbr.prevCAState, 1)
	wantEq(t, "ack 1300", "pc", f.bbr.usePacketConservation, false)
	f.caState = caOpen
	bbrAck(f, 1350, 1100, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1350", "prevca", f.bbr.prevCAState, 1)
	wantEq(t, "ack 1350", "pc", f.bbr.usePacketConservation, false)
	f.caState = caOpen
	bbrAck(f, 1400, 1300, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, losses: 5, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "prevca", f.bbr.prevCAState, 1)
	wantEq(t, "ack 1400", "pc", f.bbr.usePacketConservation, false)
	f.caState = caRecovery
	bbrAck(f, 1450, 1500, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1300, ackedSacked: 200, losses: 1, rttMS: 50})
	checkBBR(t, f, "ack 1450", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 340, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1450", "prevca", f.bbr.prevCAState, 2)
	wantEq(t, "ack 1450", "pc", f.bbr.usePacketConservation, true)
	f.caState = caRecovery
	bbrAck(f, 1500, 1700, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1500", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 540, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1500", "prevca", f.bbr.prevCAState, 2)
	wantEq(t, "ack 1500", "pc", f.bbr.usePacketConservation, false)
}

// Full bandwidth is only counted in rounds that are not app limited: three flat rounds after the
// app limited ones reach it.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRFullBWIgnoresAppLimitedRoundsLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1350", "fullbwcount", f.bbr.fullBWCount, 0)
	bbrAck(f, 1400, 1300, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1400", "fullbwcount", f.bbr.fullBWCount, 1)
	bbrAck(f, 1450, 1500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1450", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1450", "fullbwcount", f.bbr.fullBWCount, 2)
}

// A burst of acks far above the bandwidth estimate raises the degree of ack aggregation. The
// window term it adds is capped at 100 ms of packets at the current bandwidth (400 packets at 4
// packets/ms), and the stored value rotates to the other window after five rounds.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRAckAggregationCapLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1050", "rttcount", f.bbr.rttCount, 1)
	wantEq(t, "ack 1050", "delivered", f.rate.delivered, 50)
	wantEq(t, "ack 1050", "gainp", f.bbr.pacingGain, float32(2.88539004))
	wantEq(t, "ack 1050", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 400, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrDrain, cycle: 0, cwnd: 777, pacing: 1581, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1350", "gainp", f.bbr.pacingGain, float32(0.346573591))
	wantEq(t, "ack 1350", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1400, 1300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "gainp", f.bbr.pacingGain, float32(1))
	wantEq(t, "ack 1400", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1460, 1900, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1300, ackedSacked: 600, rttMS: 50})
	checkBBR(t, f, "ack 1460", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 800, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1460", "ea0", f.bbr.extraAcked[0], 200)
	wantEq(t, "ack 1460", "ea1", f.bbr.extraAcked[1], 600)
	wantEq(t, "ack 1460", "epochacked", f.bbr.ackEpochAcked, 600)
	bbrAck(f, 1520, 2100, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1520", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 800, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1520", "ea0", f.bbr.extraAcked[0], 560)
	wantEq(t, "ack 1520", "ea1", f.bbr.extraAcked[1], 600)
	wantEq(t, "ack 1520", "epochacked", f.bbr.ackEpochAcked, 800)
	bbrAck(f, 1580, 2300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1580", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 800, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1580", "ea0", f.bbr.extraAcked[0], 560)
	wantEq(t, "ack 1580", "ea1", f.bbr.extraAcked[1], 600)
	wantEq(t, "ack 1580", "epochacked", f.bbr.ackEpochAcked, 1000)
	bbrAck(f, 1640, 2500, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1640", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 800, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1640", "ea0", f.bbr.extraAcked[0], 560)
	wantEq(t, "ack 1640", "ea1", f.bbr.extraAcked[1], 600)
	wantEq(t, "ack 1640", "epochacked", f.bbr.ackEpochAcked, 1200)
	bbrAck(f, 1700, 2700, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1700", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 800, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1700", "ea0", f.bbr.extraAcked[0], 560)
	wantEq(t, "ack 1700", "ea1", f.bbr.extraAcked[1], 600)
	wantEq(t, "ack 1700", "epochacked", f.bbr.ackEpochAcked, 1400)
	wantEq(t, "ack 1700", "epochstart", f.bbr.ackEpochStart, 1460)
}

// Full bandwidth needs 25% growth in a round. A 27.5% step (4 to 5.1 packets/ms) counts as growth,
// so the three flat rounds after it are needed again.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRFullBWGrowthThresholdLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1250", "fullbwcount", f.bbr.fullBWCount, 1)
	bbrAck(f, 1300, 955, 100, rateSample{intervalMS: 50, delivered: 255, priorDelivered: 700, ackedSacked: 255, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 965, pacing: 16782, bw: 5.1, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1300", "fullbwcount", f.bbr.fullBWCount, 0)
	bbrAck(f, 1350, 1210, 100, rateSample{intervalMS: 50, delivered: 255, priorDelivered: 955, ackedSacked: 255, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrStartup, cycle: 0, cwnd: 965, pacing: 16782, bw: 5.1, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1350", "fullbwcount", f.bbr.fullBWCount, 1)
	bbrAck(f, 1400, 1465, 100, rateSample{intervalMS: 50, delivered: 255, priorDelivered: 1210, ackedSacked: 255, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrStartup, cycle: 0, cwnd: 965, pacing: 16782, bw: 5.1, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1400", "fullbwcount", f.bbr.fullBWCount, 2)
	bbrAck(f, 1450, 1720, 100, rateSample{intervalMS: 50, delivered: 255, priorDelivered: 1465, ackedSacked: 255, rttMS: 50})
	checkBBR(t, f, "ack 1450", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 765, pacing: 5816, bw: 5.1, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1450", "fullbwcount", f.bbr.fullBWCount, 3)
}

// The min RTT filter expires when more than 10 s (10000 ms) have passed since its stamp: 10999 and
// 11000 ms are still inside the window, 11001 ms is past it.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRMinRTTWindowIsTenSecondsLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 100, 10, rateSample{intervalMS: 50, delivered: 100, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 110, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 10999, 200, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 100, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 10999", bbrWant{state: bbrStartup, cycle: 0, cwnd: 210, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 11000, 300, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 200, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11000", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 11001, 400, 10, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 300, ackedSacked: 100, rttMS: 60})
	checkBBR(t, f, "ack 11001", bbrWant{state: bbrProbeRTT, cycle: 4, cwnd: 4, pacing: 2280, bw: 2.0, minRTT: 60, minStamp: 11001, fullBW: true})
}

// Until 10 packets have been delivered the window grows by the acked count even when it is already
// at the target, since the 2 packets/ms estimate is too small to hold the window back.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRStartupGrowthBelowTenPacketsLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 2, 2, rateSample{intervalMS: 50, delivered: 2, ackedSacked: 2, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 12, pacing: 658, bw: 0.04, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1100, 4, 2, rateSample{intervalMS: 50, delivered: 2, priorDelivered: 2, ackedSacked: 2, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 14, pacing: 658, bw: 0.04, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 6, 2, rateSample{intervalMS: 50, delivered: 2, priorDelivered: 4, ackedSacked: 2, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 16, pacing: 658, bw: 0.04, minRTT: 50, minStamp: 1000, fullBW: false})
}

// The max bandwidth filter keeps its best sample for 10 packet-timed rounds. Its 4 packets/ms
// samples from the ramp expire after that, and the estimate falls to the 2 packets/ms that follow.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRMaxBandwidthWindowLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1050", "rttcount", f.bbr.rttCount, 1)
	wantEq(t, "ack 1050", "delivered", f.rate.delivered, 50)
	wantEq(t, "ack 1050", "gainp", f.bbr.pacingGain, float32(2.88539004))
	wantEq(t, "ack 1050", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 400, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrDrain, cycle: 0, cwnd: 777, pacing: 1581, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1350", "gainp", f.bbr.pacingGain, float32(0.346573591))
	wantEq(t, "ack 1350", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1400, 1300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "gainp", f.bbr.pacingGain, float32(1))
	wantEq(t, "ack 1400", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1460, 1400, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1300, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1460", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1460", "rttcount", f.bbr.rttCount, 9)
	bbrAck(f, 1510, 1500, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1400, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1510", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1510", "rttcount", f.bbr.rttCount, 10)
	bbrAck(f, 1560, 1600, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1500, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1560", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1560", "rttcount", f.bbr.rttCount, 11)
	bbrAck(f, 1610, 1700, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1600, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1610", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1610", "rttcount", f.bbr.rttCount, 12)
	bbrAck(f, 1660, 1800, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1700, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1660", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1660", "rttcount", f.bbr.rttCount, 13)
	bbrAck(f, 1710, 1900, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1800, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1710", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1710", "rttcount", f.bbr.rttCount, 14)
	bbrAck(f, 1760, 2000, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1900, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1760", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1760", "rttcount", f.bbr.rttCount, 15)
	bbrAck(f, 1810, 2100, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2000, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1810", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1810", "rttcount", f.bbr.rttCount, 16)
	bbrAck(f, 1860, 2200, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2100, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1860", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1860", "rttcount", f.bbr.rttCount, 17)
	bbrAck(f, 1910, 2300, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2200, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1910", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1910", "rttcount", f.bbr.rttCount, 18)
	bbrAck(f, 1960, 2400, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2300, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1960", bbrWant{state: bbrProbeBW, cycle: 1, cwnd: 300, pacing: 1710, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1960", "rttcount", f.bbr.rttCount, 19)
	bbrAck(f, 2010, 2500, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2400, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 2010", bbrWant{state: bbrProbeBW, cycle: 1, cwnd: 300, pacing: 1710, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2010", "rttcount", f.bbr.rttCount, 20)
	bbrAck(f, 2060, 2600, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2500, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 2060", bbrWant{state: bbrProbeBW, cycle: 2, cwnd: 300, pacing: 2280, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2060", "rttcount", f.bbr.rttCount, 21)
	bbrAck(f, 2110, 2700, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2600, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 2110", bbrWant{state: bbrProbeBW, cycle: 2, cwnd: 300, pacing: 2280, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2110", "rttcount", f.bbr.rttCount, 22)
}

// App limited samples below the max bandwidth are ignored, so the estimate stays at 4 packets/ms
// even after the samples that set it have expired from the window.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRAppLimitedSamplesDoNotLowerMaxBWLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1050", "rttcount", f.bbr.rttCount, 1)
	wantEq(t, "ack 1050", "delivered", f.rate.delivered, 50)
	wantEq(t, "ack 1050", "gainp", f.bbr.pacingGain, float32(2.88539004))
	wantEq(t, "ack 1050", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 400, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrDrain, cycle: 0, cwnd: 777, pacing: 1581, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1350", "gainp", f.bbr.pacingGain, float32(0.346573591))
	wantEq(t, "ack 1350", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1400, 1300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "gainp", f.bbr.pacingGain, float32(1))
	wantEq(t, "ack 1400", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1460, 1400, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1300, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1460", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1460", "rttcount", f.bbr.rttCount, 9)
	bbrAck(f, 1510, 1500, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1400, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1510", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1510", "rttcount", f.bbr.rttCount, 10)
	bbrAck(f, 1560, 1600, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1500, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1560", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1560", "rttcount", f.bbr.rttCount, 11)
	bbrAck(f, 1610, 1700, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1600, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1610", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1610", "rttcount", f.bbr.rttCount, 12)
	bbrAck(f, 1660, 1800, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1700, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1660", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1660", "rttcount", f.bbr.rttCount, 13)
	bbrAck(f, 1710, 1900, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1800, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1710", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1710", "rttcount", f.bbr.rttCount, 14)
	bbrAck(f, 1760, 2000, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 1900, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1760", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1760", "rttcount", f.bbr.rttCount, 15)
	bbrAck(f, 1810, 2100, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2000, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1810", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1810", "rttcount", f.bbr.rttCount, 16)
	bbrAck(f, 1860, 2200, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2100, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1860", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1860", "rttcount", f.bbr.rttCount, 17)
	bbrAck(f, 1910, 2300, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2200, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1910", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1910", "rttcount", f.bbr.rttCount, 18)
	bbrAck(f, 1960, 2400, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2300, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 1960", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1960", "rttcount", f.bbr.rttCount, 19)
	bbrAck(f, 2010, 2500, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2400, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 2010", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2010", "rttcount", f.bbr.rttCount, 20)
	bbrAck(f, 2060, 2600, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2500, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 2060", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2060", "rttcount", f.bbr.rttCount, 21)
	bbrAck(f, 2110, 2700, 150, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 2600, ackedSacked: 100, rttMS: 50, isAppLimited: true})
	checkBBR(t, f, "ack 2110", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 500, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2110", "rttcount", f.bbr.rttCount, 22)
}

// Phase rules in PROBE_BW. A phase ends once it has run a min RTT (50 ms here). Inside that time
// the 1.25 phase still holds without losses, and the 0.75 phase ends early once the in-flight
// count is at or under the BDP at gain 1.0.
// Upstream run: libudx ae8bff7 src/udx_bbr.c through the scratch C harness.
func TestBBRProbeBWPhaseRulesLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10, srtt: 50}
	f.initBBR(1000, 50)
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 658, bw: 0.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1050, 50, 40, rateSample{intervalMS: 50, delivered: 50, ackedSacked: 50, rttMS: 50})
	checkBBR(t, f, "ack 1050", bbrWant{state: bbrStartup, cycle: 0, cwnd: 60, pacing: 3290, bw: 1.0, minRTT: 50, minStamp: 1000, fullBW: false})
	wantEq(t, "ack 1050", "rttcount", f.bbr.rttCount, 1)
	wantEq(t, "ack 1050", "delivered", f.rate.delivered, 50)
	wantEq(t, "ack 1050", "gainp", f.bbr.pacingGain, float32(2.88539004))
	wantEq(t, "ack 1050", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1100, 150, 60, rateSample{intervalMS: 50, delivered: 100, priorDelivered: 50, ackedSacked: 100, rttMS: 50})
	checkBBR(t, f, "ack 1100", bbrWant{state: bbrStartup, cycle: 0, cwnd: 160, pacing: 6581, bw: 2.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1150, 300, 80, rateSample{intervalMS: 50, delivered: 150, priorDelivered: 150, ackedSacked: 150, rttMS: 50})
	checkBBR(t, f, "ack 1150", bbrWant{state: bbrStartup, cycle: 0, cwnd: 310, pacing: 9872, bw: 3.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1200, 500, 100, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1200", bbrWant{state: bbrStartup, cycle: 0, cwnd: 510, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1250, 700, 120, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1250", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1300, 900, 140, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1300", bbrWant{state: bbrStartup, cycle: 0, cwnd: 710, pacing: 13162, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: false})
	bbrAck(f, 1350, 1100, 400, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1350", bbrWant{state: bbrDrain, cycle: 0, cwnd: 777, pacing: 1581, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1350", "gainp", f.bbr.pacingGain, float32(0.346573591))
	wantEq(t, "ack 1350", "gainc", f.bbr.cwndGain, float32(2.88539004))
	bbrAck(f, 1400, 1300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1400", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1400", "gainp", f.bbr.pacingGain, float32(1))
	wantEq(t, "ack 1400", "gainc", f.bbr.cwndGain, float32(2))
	bbrAck(f, 1460, 1500, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1460", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1520, 1700, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1520", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1580, 1900, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1580", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 600, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	bbrAck(f, 1640, 2100, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 1900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1640", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 600, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1640", "cyclets", f.bbr.cycleTimestamp, 1640)
	bbrAck(f, 1670, 2300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2100, ackedSacked: 200, losses: 1, rttMS: 50})
	checkBBR(t, f, "ack 1670", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 680, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1670", "cyclets", f.bbr.cycleTimestamp, 1640)
	bbrAck(f, 1740, 2500, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1740", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 680, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1740", "cyclets", f.bbr.cycleTimestamp, 1640)
	bbrAck(f, 1800, 2700, 300, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1800", bbrWant{state: bbrProbeBW, cycle: 1, cwnd: 680, pacing: 3421, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1800", "cyclets", f.bbr.cycleTimestamp, 1800)
	bbrAck(f, 1820, 2900, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1820", bbrWant{state: bbrProbeBW, cycle: 2, cwnd: 720, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1820", "cyclets", f.bbr.cycleTimestamp, 1820)
	bbrAck(f, 1880, 3100, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 2900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1880", bbrWant{state: bbrProbeBW, cycle: 3, cwnd: 720, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1880", "cyclets", f.bbr.cycleTimestamp, 1880)
	bbrAck(f, 1940, 3300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 3100, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 1940", bbrWant{state: bbrProbeBW, cycle: 4, cwnd: 720, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 1940", "cyclets", f.bbr.cycleTimestamp, 1940)
	bbrAck(f, 2000, 3500, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 3300, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 2000", bbrWant{state: bbrProbeBW, cycle: 5, cwnd: 720, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2000", "cyclets", f.bbr.cycleTimestamp, 2000)
	bbrAck(f, 2060, 3700, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 3500, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 2060", bbrWant{state: bbrProbeBW, cycle: 6, cwnd: 720, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2060", "cyclets", f.bbr.cycleTimestamp, 2060)
	bbrAck(f, 2120, 3900, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 3700, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 2120", bbrWant{state: bbrProbeBW, cycle: 7, cwnd: 720, pacing: 4561, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2120", "cyclets", f.bbr.cycleTimestamp, 2120)
	bbrAck(f, 2180, 4100, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 3900, ackedSacked: 200, rttMS: 50})
	checkBBR(t, f, "ack 2180", bbrWant{state: bbrProbeBW, cycle: 0, cwnd: 720, pacing: 5702, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2180", "cyclets", f.bbr.cycleTimestamp, 2180)
	bbrAck(f, 2240, 4300, 150, rateSample{intervalMS: 50, delivered: 200, priorDelivered: 4100, ackedSacked: 200, losses: 1, rttMS: 50})
	checkBBR(t, f, "ack 2240", bbrWant{state: bbrProbeBW, cycle: 1, cwnd: 720, pacing: 3421, bw: 4.0, minRTT: 50, minStamp: 1000, fullBW: true})
	wantEq(t, "ack 2240", "cyclets", f.bbr.cycleTimestamp, 2240)
}

// A flow with no RTT sample yet: the pacing rate starts from cwnd over 1 ms, has_seen_rtt stays
// false, and the min RTT is the filter's reset value (~0) until a sample arrives. Upstream run:
// bbr_init with srtt 0 and udx_rtt_min ~0.
func TestBBRInitWithoutRTTSampleLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{cwnd: 10}
	f.initBBR(1000, ^uint32(0))
	checkBBR(t, f, "init", bbrWant{state: bbrStartup, cycle: 0, cwnd: 10, pacing: 32907, bw: 0, minRTT: ^uint32(0), minStamp: 1000, fullBW: false})
	wantEq(t, "init", "hasrtt", f.bbr.hasSeenRTT, false)
	wantEq(t, "init", "prevca", f.bbr.prevCAState, caOpen)
	wantEq(t, "init", "epochstart", f.bbr.ackEpochStart, uint64(1000))
}

// The helpers that udx_bbr.c computes with: the pacing rate (bw x mss x gain x 0.99, truncated,
// at least 1), the BDP (bw x min RTT x gain, at least 1 packet, 10 before any RTT sample), and
// the two time differences. Upstream values come from the C helpers themselves.
func TestBBRHelpersLikeUpstream(t *testing.T) {
	defer failOnPanic(t)
	f := &bbrFlow{}
	wantEq(t, "helpers", "pacing 0.1 x high gain", f.bwToPacingRate(0.1, 2.88539), uint64(329))
	wantEq(t, "helpers", "pacing 10 x 1.0", f.bwToPacingRate(10, 1.0), uint64(11404))
	wantEq(t, "helpers", "pacing 0 is at least 1", f.bwToPacingRate(0, 2.0), uint64(1))
	wantEq(t, "helpers", "pacing 0.001 x 1.0 is at least 1", f.bwToPacingRate(0.001, 1.0), uint64(1))

	f.bbr.minRTTms = 100
	wantEq(t, "helpers", "bdp 0.1 x 100", f.bdp(0.1, 1.0), uint32(10))
	wantEq(t, "helpers", "bdp 0.05 x 100", f.bdp(0.05, 1.0), uint32(5))
	wantEq(t, "helpers", "bdp is at least 1", f.bdp(0.001, 1.0), uint32(1))
	f.bbr.minRTTms = ^uint32(0)
	wantEq(t, "helpers", "bdp before any RTT sample is 10", f.bdp(0.5, 2.0), uint32(10))

	wantEq(t, "helpers", "time_delta_ms forward", timeDeltaMS(1120, 1000), uint32(120))
	// time_delta_ms converts a negative difference to uint32 without clamping, so it wraps.
	wantEq(t, "helpers", "time_delta_ms backward wraps", timeDeltaMS(1000, 1120), uint32(4294967176))
	wantEq(t, "helpers", "time_diff backward is signed", timeDiff(1000, 1120), int64(-120))
	wantEq(t, "helpers", "time_diff forward", timeDiff(1120, 1000), int64(120))
}
