package secretstream

import (
	"bytes"
	"testing"

	"github.com/andrewloable/HoleBridge/internal/testvec"
)

// vector is spec/vectors/sodium-secretstream.json, generated by spec/gen/sodium-secretstream.js.
type vector struct {
	Key      string `json:"key"`
	Header   string `json:"header"`
	Messages []struct {
		Tag        byte   `json:"tag"`
		AD         string `json:"ad"`
		Message    string `json:"message"`
		Ciphertext string `json:"ciphertext"`
	} `json:"messages"`
}

// mustNotPanic runs f and fails t, with the panic value as the message, if f panics. The stubs
// panic until the IMPL task lands; this keeps one stub call from ending the whole test binary.
func mustNotPanic(t *testing.T, f func()) {
	t.Helper()
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("panic: %v", r)
		}
	}()
	f()
}

func keyAndHeader(t *testing.T, v vector) ([32]byte, [24]byte) {
	t.Helper()
	var key [32]byte
	var header [24]byte
	k, h := testvec.Hex(t, v.Key), testvec.Hex(t, v.Header)
	if len(k) != len(key) || len(h) != len(header) {
		t.Fatalf("vector key is %d bytes and header %d, want 32 and 24", len(k), len(h))
	}
	copy(key[:], k)
	copy(header[:], h)
	return key, header
}

// sealVector seals every message of v, in order, with a Push that uses the vector's header.
func sealVector(t *testing.T, v vector) [][]byte {
	t.Helper()
	key, header := keyAndHeader(t, v)
	var out [][]byte
	mustNotPanic(t, func() {
		push := newPushWithHeader(key, header)
		for _, m := range v.Messages {
			out = append(out, push.Seal(testvec.Hex(t, m.Message), testvec.Hex(t, m.AD), m.Tag))
		}
	})
	return out
}

func loadVector(t *testing.T) vector {
	t.Helper()
	var v vector
	testvec.Load(t, "sodium-secretstream.json", &v)
	return v
}

// Pull opens every ciphertext in the vector to its message and tag.
func TestPullOpensVector(t *testing.T) {
	v := loadVector(t)
	key, header := keyAndHeader(t, v)
	var pull *Pull
	mustNotPanic(t, func() { pull = NewPull(key, header) })
	for i, m := range v.Messages {
		msg, tag, err := pull.Open(testvec.Hex(t, m.Ciphertext), testvec.Hex(t, m.AD))
		if err != nil {
			t.Fatalf("message %d: Open: %v", i, err)
		}
		if !bytes.Equal(msg, testvec.Hex(t, m.Message)) {
			t.Errorf("message %d: plaintext differs from the vector", i)
		}
		if tag != m.Tag {
			t.Errorf("message %d: tag = %d, want %d", i, tag, m.Tag)
		}
	}
}

// Push with the vector's header seals every message to the vector's ciphertext.
func TestPushSealsVector(t *testing.T) {
	v := loadVector(t)
	got := sealVector(t, v)
	for i, m := range v.Messages {
		if !bytes.Equal(got[i], testvec.Hex(t, m.Ciphertext)) {
			t.Errorf("message %d (tag %d): ciphertext differs from the vector", i, m.Tag)
		}
	}
}

// A flipped ciphertext bit fails Open. The unchanged ciphertext must open first, so the test cannot
// pass on a stub that always returns an error.
func TestPullRejectsFlippedBit(t *testing.T) {
	v := loadVector(t)
	key, header := keyAndHeader(t, v)
	ct := testvec.Hex(t, v.Messages[0].Ciphertext)
	ad := testvec.Hex(t, v.Messages[0].AD)
	open := func(ct []byte) error {
		var err error
		mustNotPanic(t, func() {
			_, _, err = NewPull(key, header).Open(ct, ad)
		})
		return err
	}
	if err := open(ct); err != nil {
		t.Fatalf("unchanged ciphertext: Open: %v", err)
	}
	for i := range ct {
		ct[i] ^= 1
		if err := open(ct); err == nil {
			t.Errorf("bit 0 of byte %d flipped: Open accepted the ciphertext", i)
		}
		ct[i] ^= 1
	}
}

// Messages opened out of order fail. Opening the first two in order must succeed, so the test
// cannot pass on a stub that always returns an error.
func TestPullRejectsOutOfOrder(t *testing.T) {
	v := loadVector(t)
	key, header := keyAndHeader(t, v)
	var inOrder, outOfOrder *Pull
	mustNotPanic(t, func() {
		inOrder = NewPull(key, header)
		outOfOrder = NewPull(key, header)
	})
	for i := 0; i < 2; i++ {
		ct, ad := testvec.Hex(t, v.Messages[i].Ciphertext), testvec.Hex(t, v.Messages[i].AD)
		if _, _, err := inOrder.Open(ct, ad); err != nil {
			t.Fatalf("message %d opened in order: Open: %v", i, err)
		}
	}
	ct, ad := testvec.Hex(t, v.Messages[1].Ciphertext), testvec.Hex(t, v.Messages[1].AD)
	if _, _, err := outOfOrder.Open(ct, ad); err == nil {
		t.Errorf("message 1 opened before message 0: Open accepted it")
	}
}

// After TagRekey the next messages still match the vector.
func TestSealAfterRekeyMatchesVector(t *testing.T) {
	v := loadVector(t)
	rekey := -1
	for i, m := range v.Messages {
		if m.Tag == TagRekey {
			rekey = i
			break
		}
	}
	if rekey < 0 || rekey == len(v.Messages)-1 {
		t.Fatalf("vector needs a TagRekey message with messages after it")
	}
	got := sealVector(t, v)
	for i := rekey + 1; i < len(v.Messages); i++ {
		if !bytes.Equal(got[i], testvec.Hex(t, v.Messages[i].Ciphertext)) {
			t.Errorf("message %d, after the rekey at %d: ciphertext differs from the vector", i, rekey)
		}
	}
}
