package noise

import (
	"bytes"
	"testing"

	"github.com/andrewloable/HoleBridge/internal/testvec"
)

// vector is spec/vectors/noise.json, generated by spec/gen/noise.js.
type vector struct {
	Prologue  string `json:"prologue"`
	Hash      string `json:"hash"`
	Message1  string `json:"message1"`
	Message2  string `json:"message2"`
	Initiator party  `json:"initiator"`
	Responder party  `json:"responder"`
}

// party is one side of the handshake in the vector.
type party struct {
	Static    keyJSON `json:"static"`
	Ephemeral keyJSON `json:"ephemeral"`
	Payload   string  `json:"payload"`
	Tx        string  `json:"tx"`
	Rx        string  `json:"rx"`
}

// keyJSON is a key pair in the vector: the public key, and the secret in libsodium's layout.
type keyJSON struct {
	Public string `json:"public"`
	Secret string `json:"secret"`
}

func loadVector(t *testing.T) vector {
	t.Helper()
	var v vector
	testvec.Load(t, "noise.json", &v)
	return v
}

// mustNotPanic runs f and fails t, with the panic value as the message, if f panics. The stubs
// panic until the IMPL task lands; this keeps one stub call from ending the whole test binary.
func mustNotPanic(t *testing.T, f func()) {
	t.Helper()
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("panic: %v", r)
		}
	}()
	f()
}

// decodeInto fills dst with the vector value s, which must be exactly len(dst) bytes.
func decodeInto(t *testing.T, dst []byte, s string) {
	t.Helper()
	b := testvec.Hex(t, s)
	if len(b) != len(dst) {
		t.Fatalf("vector value is %d bytes, want %d", len(b), len(dst))
	}
	copy(dst, b)
}

func hex32(t *testing.T, s string) [32]byte {
	t.Helper()
	var b [32]byte
	decodeInto(t, b[:], s)
	return b
}

func hex64(t *testing.T, s string) [64]byte {
	t.Helper()
	var b [64]byte
	decodeInto(t, b[:], s)
	return b
}

// keyPair reads a key pair from the vector.
func keyPair(t *testing.T, k keyJSON) KeyPair {
	t.Helper()
	var kp KeyPair
	decodeInto(t, kp.Public[:], k.Public)
	decodeInto(t, kp.Secret[:], k.Secret)
	return kp
}

// fixEphemeral makes the next ephemeral key a handshake draws the one the vector records. The key is
// drawn from its 32-byte seed, the first half of the recorded secret. The default source comes back
// when the test ends.
func fixEphemeral(t *testing.T, k keyJSON) {
	t.Helper()
	var secret [64]byte
	decodeInto(t, secret[:], k.Secret)
	old := ephemeralRand
	t.Cleanup(func() { ephemeralRand = old })
	ephemeralRand = bytes.NewReader(secret[:32])
}

// With the vector's keys, the initiator's message 1 is byte for byte the one the vector records.
func TestInitiatorMessage1MatchesVector(t *testing.T) {
	v := loadVector(t)
	fixEphemeral(t, v.Initiator.Ephemeral)
	var msg []byte
	var err error
	mustNotPanic(t, func() {
		h := NewInitiator(keyPair(t, v.Initiator.Static), hex32(t, v.Responder.Static.Public), testvec.Hex(t, v.Prologue))
		msg, err = h.Send(testvec.Hex(t, v.Initiator.Payload))
	})
	if err != nil {
		t.Fatalf("Send: %v", err)
	}
	if !bytes.Equal(msg, testvec.Hex(t, v.Message1)) {
		t.Errorf("message 1 differs from the vector")
	}
}

// The responder with the vector's static key reads message 1 and gets the initiator's payload. The
// message 2 it sends in reply is the one the vector records.
func TestResponderMessage2MatchesVector(t *testing.T) {
	v := loadVector(t)
	fixEphemeral(t, v.Responder.Ephemeral)
	var h *Handshake
	var payload, msg []byte
	var err error
	mustNotPanic(t, func() {
		h = NewResponder(keyPair(t, v.Responder.Static), testvec.Hex(t, v.Prologue))
		payload, err = h.Recv(testvec.Hex(t, v.Message1))
	})
	if err != nil {
		t.Fatalf("Recv message 1: %v", err)
	}
	if !bytes.Equal(payload, testvec.Hex(t, v.Initiator.Payload)) {
		t.Errorf("message 1 carries a different payload than the vector")
	}
	mustNotPanic(t, func() { msg, err = h.Send(testvec.Hex(t, v.Responder.Payload)) })
	if err != nil {
		t.Fatalf("Send: %v", err)
	}
	if !bytes.Equal(msg, testvec.Hex(t, v.Message2)) {
		t.Errorf("message 2 differs from the vector")
	}
}

// After a full exchange, both sides hold the vector's transport keys and handshake hash, and each
// has the other's static public key.
func TestHandshakeKeysMatchVector(t *testing.T) {
	v := loadVector(t)
	prologue := testvec.Hex(t, v.Prologue)
	var ini, resp *Handshake
	var msg1, msg2, payload2 []byte
	var err error

	fixEphemeral(t, v.Initiator.Ephemeral)
	mustNotPanic(t, func() {
		ini = NewInitiator(keyPair(t, v.Initiator.Static), hex32(t, v.Responder.Static.Public), prologue)
		msg1, err = ini.Send(testvec.Hex(t, v.Initiator.Payload))
	})
	if err != nil {
		t.Fatalf("initiator Send: %v", err)
	}

	fixEphemeral(t, v.Responder.Ephemeral)
	mustNotPanic(t, func() {
		resp = NewResponder(keyPair(t, v.Responder.Static), prologue)
		_, err = resp.Recv(msg1)
	})
	if err != nil {
		t.Fatalf("responder Recv: %v", err)
	}
	mustNotPanic(t, func() { msg2, err = resp.Send(testvec.Hex(t, v.Responder.Payload)) })
	if err != nil {
		t.Fatalf("responder Send: %v", err)
	}

	mustNotPanic(t, func() { payload2, err = ini.Recv(msg2) })
	if err != nil {
		t.Fatalf("initiator Recv: %v", err)
	}
	if !bytes.Equal(payload2, testvec.Hex(t, v.Responder.Payload)) {
		t.Errorf("message 2 carries a different payload than the vector")
	}

	var iTx, iRx, rTx, rRx [32]byte
	var iHash, rHash [64]byte
	var iRemote, rRemote [32]byte
	mustNotPanic(t, func() {
		if !ini.Complete() {
			t.Error("initiator is not complete after message 2")
		}
		if !resp.Complete() {
			t.Error("responder is not complete after message 2")
		}
		iTx, iRx, iHash, iRemote = ini.Result()
		rTx, rRx, rHash, rRemote = resp.Result()
	})

	if iTx != hex32(t, v.Initiator.Tx) {
		t.Errorf("initiator tx differs from the vector")
	}
	if iRx != hex32(t, v.Initiator.Rx) {
		t.Errorf("initiator rx differs from the vector")
	}
	if rTx != hex32(t, v.Responder.Tx) {
		t.Errorf("responder tx differs from the vector")
	}
	if rRx != hex32(t, v.Responder.Rx) {
		t.Errorf("responder rx differs from the vector")
	}
	if iHash != hex64(t, v.Hash) {
		t.Errorf("initiator hash differs from the vector")
	}
	if rHash != hex64(t, v.Hash) {
		t.Errorf("responder hash differs from the vector")
	}
	if iRemote != hex32(t, v.Responder.Static.Public) {
		t.Errorf("initiator's remote static key differs from the responder's public key")
	}
	if rRemote != hex32(t, v.Initiator.Static.Public) {
		t.Errorf("responder's remote static key differs from the initiator's public key")
	}
}

// A responder whose static key is not the one the initiator addressed fails to read message 1. The
// responder with the right key reads the same message first, so the test cannot pass on a Recv that
// always fails.
func TestWrongResponderStaticFails(t *testing.T) {
	v := loadVector(t)
	prologue := testvec.Hex(t, v.Prologue)
	var ini *Handshake
	var msg1 []byte
	var err error
	mustNotPanic(t, func() {
		ini = NewInitiator(keyPair(t, v.Initiator.Static), hex32(t, v.Responder.Static.Public), prologue)
		msg1, err = ini.Send(testvec.Hex(t, v.Initiator.Payload))
	})
	if err != nil {
		t.Fatalf("initiator Send: %v", err)
	}

	var right *Handshake
	mustNotPanic(t, func() {
		right = NewResponder(keyPair(t, v.Responder.Static), prologue)
		_, err = right.Recv(msg1)
	})
	if err != nil {
		t.Fatalf("responder with the right static key: Recv: %v", err)
	}

	// The wrong responder holds the initiator's key pair in place of its own.
	var wrong *Handshake
	mustNotPanic(t, func() {
		wrong = NewResponder(keyPair(t, v.Initiator.Static), prologue)
		_, err = wrong.Recv(msg1)
	})
	if err == nil {
		t.Error("responder with the wrong static key accepted message 1")
	}
	var complete bool
	mustNotPanic(t, func() { complete = wrong.Complete() })
	if complete {
		t.Error("responder with the wrong static key completed the handshake")
	}
}

// A message with any one byte flipped fails Recv, for both messages. The untampered message is
// accepted first, so the test cannot pass on a Recv that always fails.
func TestTamperedMessageFailsRecv(t *testing.T) {
	v := loadVector(t)
	prologue := testvec.Hex(t, v.Prologue)
	payload1 := testvec.Hex(t, v.Initiator.Payload)
	msg1 := testvec.Hex(t, v.Message1)
	msg2 := testvec.Hex(t, v.Message2)

	// responderRecv returns the error from a fresh responder reading msg.
	responderRecv := func(msg []byte) error {
		var err error
		mustNotPanic(t, func() {
			h := NewResponder(keyPair(t, v.Responder.Static), prologue)
			_, err = h.Recv(msg)
		})
		return err
	}
	if err := responderRecv(msg1); err != nil {
		t.Fatalf("untampered message 1: Recv: %v", err)
	}
	for i := range msg1 {
		bad := bytes.Clone(msg1)
		bad[i] ^= 1
		if responderRecv(bad) == nil {
			t.Errorf("message 1 with byte %d flipped: Recv accepted it", i)
		}
	}

	// initiatorRecv returns the error from a fresh initiator reading msg. The initiator sends first,
	// with the vector's ephemeral key, so msg is the responder's reply to that message 1.
	initiatorRecv := func(msg []byte) error {
		fixEphemeral(t, v.Initiator.Ephemeral)
		var err error
		mustNotPanic(t, func() {
			h := NewInitiator(keyPair(t, v.Initiator.Static), hex32(t, v.Responder.Static.Public), prologue)
			if _, err = h.Send(payload1); err != nil {
				return
			}
			_, err = h.Recv(msg)
		})
		return err
	}
	if err := initiatorRecv(msg2); err != nil {
		t.Fatalf("untampered message 2: Recv: %v", err)
	}
	for i := range msg2 {
		bad := bytes.Clone(msg2)
		bad[i] ^= 1
		if initiatorRecv(bad) == nil {
			t.Errorf("message 2 with byte %d flipped: Recv accepted it", i)
		}
	}
}
